/*
 * Sample usage:
 * $ cc -I/usr/local/include make-drm-render-conf.c
 * $ ./a.out > /usr/local/etc/curtain.d/_drm_render.conf
 */

#include <stdio.h>
#include <sys/param.h>

#include <sys/pciio.h>

#include <libdrm/drm.h>
#include <libdrm/amdgpu_drm.h>
#include <libdrm/i915_drm.h>
#include <libdrm/radeon_drm.h>
#include <libdrm/vmwgfx_drm.h>

static const struct { unsigned long ioctl; const char *name; } table[] = {
#define	ENTRY(name) { name, #name }
	ENTRY(PCIOCGETCONF),

	ENTRY(DRM_IOCTL_VERSION),
	ENTRY(DRM_IOCTL_GET_CAP),
#ifdef	DRM_IOCTL_GET_PCIINFO
	ENTRY(DRM_IOCTL_GET_PCIINFO),
#endif
	ENTRY(DRM_IOCTL_GEM_CLOSE),
	ENTRY(DRM_IOCTL_PRIME_HANDLE_TO_FD),
	ENTRY(DRM_IOCTL_PRIME_FD_TO_HANDLE),
	ENTRY(DRM_IOCTL_SYNCOBJ_CREATE),
	ENTRY(DRM_IOCTL_SYNCOBJ_DESTROY),
	ENTRY(DRM_IOCTL_SYNCOBJ_HANDLE_TO_FD),
	ENTRY(DRM_IOCTL_SYNCOBJ_FD_TO_HANDLE),
	ENTRY(DRM_IOCTL_SYNCOBJ_TRANSFER),
	ENTRY(DRM_IOCTL_SYNCOBJ_WAIT),
	ENTRY(DRM_IOCTL_SYNCOBJ_TIMELINE_WAIT),
	ENTRY(DRM_IOCTL_SYNCOBJ_RESET),
	ENTRY(DRM_IOCTL_SYNCOBJ_SIGNAL),
	ENTRY(DRM_IOCTL_SYNCOBJ_TIMELINE_SIGNAL),
	ENTRY(DRM_IOCTL_SYNCOBJ_QUERY),

	ENTRY(DRM_IOCTL_AMDGPU_GEM_CREATE),
	ENTRY(DRM_IOCTL_AMDGPU_CTX),
	ENTRY(DRM_IOCTL_AMDGPU_VM),
	ENTRY(DRM_IOCTL_AMDGPU_BO_LIST),
	ENTRY(DRM_IOCTL_AMDGPU_FENCE_TO_HANDLE),
	ENTRY(DRM_IOCTL_AMDGPU_GEM_MMAP),
	ENTRY(DRM_IOCTL_AMDGPU_GEM_WAIT_IDLE),
	ENTRY(DRM_IOCTL_AMDGPU_CS),
	ENTRY(DRM_IOCTL_AMDGPU_INFO),
	ENTRY(DRM_IOCTL_AMDGPU_WAIT_CS),
	ENTRY(DRM_IOCTL_AMDGPU_WAIT_FENCES),
	ENTRY(DRM_IOCTL_AMDGPU_GEM_METADATA),
	ENTRY(DRM_IOCTL_AMDGPU_GEM_VA),
	ENTRY(DRM_IOCTL_AMDGPU_GEM_OP),
	ENTRY(DRM_IOCTL_AMDGPU_GEM_USERPTR),

	ENTRY(DRM_IOCTL_I915_GETPARAM),
	ENTRY(DRM_IOCTL_I915_GEM_EXECBUFFER2_WR),
	ENTRY(DRM_IOCTL_I915_GEM_BUSY),
	ENTRY(DRM_IOCTL_I915_GEM_SET_CACHING),
	ENTRY(DRM_IOCTL_I915_GEM_GET_CACHING),
	ENTRY(DRM_IOCTL_I915_GEM_THROTTLE),
	ENTRY(DRM_IOCTL_I915_GEM_CREATE),
	ENTRY(DRM_IOCTL_I915_GEM_PREAD),
	ENTRY(DRM_IOCTL_I915_GEM_PWRITE),
	ENTRY(DRM_IOCTL_I915_GEM_MMAP),
	ENTRY(DRM_IOCTL_I915_GEM_MMAP_GTT),
	ENTRY(DRM_IOCTL_I915_GEM_SET_DOMAIN),
	ENTRY(DRM_IOCTL_I915_GEM_SW_FINISH),
	ENTRY(DRM_IOCTL_I915_GEM_SET_TILING),
	ENTRY(DRM_IOCTL_I915_GEM_GET_TILING),
	ENTRY(DRM_IOCTL_I915_GEM_GET_APERTURE),
	ENTRY(DRM_IOCTL_I915_GEM_MADVISE),
	ENTRY(DRM_IOCTL_I915_GEM_WAIT),
	ENTRY(DRM_IOCTL_I915_GEM_CONTEXT_CREATE_EXT),
	ENTRY(DRM_IOCTL_I915_GEM_CONTEXT_DESTROY),
	ENTRY(DRM_IOCTL_I915_REG_READ),
	ENTRY(DRM_IOCTL_I915_GET_RESET_STATS),
	ENTRY(DRM_IOCTL_I915_GEM_USERPTR),
	ENTRY(DRM_IOCTL_I915_GEM_CONTEXT_GETPARAM),
	ENTRY(DRM_IOCTL_I915_GEM_CONTEXT_SETPARAM),
	ENTRY(DRM_IOCTL_I915_PERF_OPEN),
	ENTRY(DRM_IOCTL_I915_PERF_ADD_CONFIG),
	ENTRY(DRM_IOCTL_I915_PERF_REMOVE_CONFIG),
	ENTRY(DRM_IOCTL_I915_QUERY),
#ifdef	DRM_IOCTL_I915_GEM_VM_CREATE
	ENTRY(DRM_IOCTL_I915_GEM_VM_CREATE),
#endif
#ifdef	DRM_IOCTL_I915_GEM_VM_DESTROY
	ENTRY(DRM_IOCTL_I915_GEM_VM_DESTROY),
#endif

	ENTRY(DRM_IOCTL_RADEON_GEM_INFO),
	ENTRY(DRM_IOCTL_RADEON_GEM_CREATE),
	ENTRY(DRM_IOCTL_RADEON_GEM_MMAP),
	ENTRY(DRM_IOCTL_RADEON_GEM_SET_DOMAIN),
	ENTRY(DRM_IOCTL_RADEON_GEM_WAIT_IDLE),
	ENTRY(DRM_IOCTL_RADEON_CS),
	ENTRY(DRM_IOCTL_RADEON_INFO),
	ENTRY(DRM_IOCTL_RADEON_GEM_SET_TILING),
	ENTRY(DRM_IOCTL_RADEON_GEM_GET_TILING),
	ENTRY(DRM_IOCTL_RADEON_GEM_BUSY),
	ENTRY(DRM_IOCTL_RADEON_GEM_VA),
	ENTRY(DRM_IOCTL_RADEON_GEM_OP),
	ENTRY(DRM_IOCTL_RADEON_GEM_USERPTR),

	ENTRY(DRM_VMW_GET_PARAM),
	ENTRY(DRM_VMW_ALLOC_DMABUF),
	ENTRY(DRM_VMW_UNREF_DMABUF),
	ENTRY(DRM_VMW_CREATE_SURFACE),
	ENTRY(DRM_VMW_UNREF_SURFACE),
	ENTRY(DRM_VMW_REF_SURFACE),
	ENTRY(DRM_VMW_EXECBUF),
	ENTRY(DRM_VMW_FENCE_WAIT),
	ENTRY(DRM_VMW_FENCE_SIGNALED),
	ENTRY(DRM_VMW_FENCE_UNREF),
	ENTRY(DRM_VMW_FENCE_EVENT),
	ENTRY(DRM_VMW_GET_3D_CAP),
	ENTRY(DRM_VMW_UPDATE_LAYOUT),
	ENTRY(DRM_VMW_CREATE_SHADER),
	ENTRY(DRM_VMW_UNREF_SHADER),
	ENTRY(DRM_VMW_GB_SURFACE_CREATE),
	ENTRY(DRM_VMW_GB_SURFACE_REF),
	ENTRY(DRM_VMW_SYNCCPU),
	ENTRY(DRM_VMW_CREATE_EXTENDED_CONTEXT),
#ifdef	DRM_VMW_GB_SURFACE_CREATE_EXT
	ENTRY(DRM_VMW_GB_SURFACE_CREATE_EXT),
#endif
#ifdef	DRM_VMW_GB_SURFACE_REF_EXT
	ENTRY(DRM_VMW_GB_SURFACE_REF_EXT),
#endif
#undef	ENTRY
};

int main() {
	printf("merge _drm_base\n");
	for (size_t i = 0; i < nitems(table); i++)
		printf("ioctl %#010lx # %s\n", table[i].ioctl, table[i].name);
	return (0);
}
