#include <curtain.h>

#include <sys/socket.h>
#include <netinet/in.h>
#include <netinet/tcp.h>

const int curtain_sockopts_basic[][2] = {
	{ SOL_SOCKET, SO_ERROR },
	{ SOL_SOCKET, SO_REUSEADDR },
	{ SOL_SOCKET, SO_REUSEPORT },
	{ SOL_SOCKET, SO_REUSEPORT_LB },
	{ SOL_SOCKET, SO_KEEPALIVE },
	{ SOL_SOCKET, SO_LINGER },
	{ SOL_SOCKET, SO_SNDBUF },
	{ SOL_SOCKET, SO_RCVBUF },
	{ SOL_SOCKET, SO_SNDLOWAT },
	{ SOL_SOCKET, SO_RCVLOWAT },
	{ SOL_SOCKET, SO_SNDTIMEO },
	{ SOL_SOCKET, SO_RCVTIMEO },
	{ SOL_SOCKET, SO_NOSIGPIPE },
	{ SOL_SOCKET, SO_TIMESTAMP },
	{ SOL_SOCKET, SO_BINTIME },
	{ SOL_SOCKET, SO_ACCEPTCONN },
	{ SOL_SOCKET, SO_DOMAIN },
	{ SOL_SOCKET, SO_TYPE },
	{ SOL_SOCKET, SO_PROTOCOL },
	{ SOL_SOCKET, SO_PROTOTYPE },
#if 0
	{ SOL_SOCKET, SO_BROADCAST },
	{ SOL_SOCKET, SO_SETFIB },
	{ SOL_SOCKET, SO_LABEL },
	{ SOL_SOCKET, SO_PEERLABEL },
#endif
	{ -1, -1 },
};

const int curtain_sockopts_inet[][2] = {
	{ IPPROTO_IP, IP_RECVDSTADDR },
	{ IPPROTO_IP, IP_TOS },
	{ IPPROTO_IPV6, IPV6_V6ONLY },
	{ IPPROTO_IPV6, IPV6_TCLASS },
	{ IPPROTO_TCP, TCP_NODELAY },
	{ IPPROTO_TCP, TCP_MAXSEG },
	{ IPPROTO_TCP, TCP_NOPUSH },
	{ -1, -1 },
};
